### ISSUE TITLE
When will code be available?

### ISSUE THREAD

**Issue by crazyofapple** [danishpruthi/evaluating-explanations#1]
Thanks.

**Comment by danishpruthi** [comment]
Thanks for your interest, and sorry for the delay. 

If you are looking to evaluate explanations using our metric, you can use the [this repository](https://github.com/CoderPat/learning-scaffold) instead as this: (1) computes our proposed simulatability metric and also generates explanations that are optimized according to our metric, and (2) is a modern reimplementation of our work, and (iii) is overall better structured and maintained.
